In [168]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.2)
Requirement already satisfied: openpyxl in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.52)
Requirement already satisfied: pymysql in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: et-xmlfile in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\princ\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [169]:
import pandas as pd
import numpy as np

In [170]:
df=pd.read_excel('Ecommerce_Unclean_Project.xlsx')

In [171]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [172]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 61.5+ KB

In [173]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [174]:
df.shape

(524, 15)

In [175]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [176]:
df.duplicated().sum()

np.int64(11)

In [177]:
df.drop_duplicates(inplace=True)

In [178]:
df.duplicated().sum()

np.int64(0)

In [179]:
df.replace(['N/A','NULL',''],np.nan,inplace=True)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [180]:
df=df.apply(lambda x: x.str.strip() if x.dtype=='object' else x)

In [181]:
df['Customer_name']=df['Customer_Name'].str.title()
df['City']=df['City'].str.title()
df['State']=df['State'].str.title()

In [182]:
df=df[df['Email'].str.contains('@',na=False)]

In [183]:
df['Order_Date']=pd.to_datetime(df['Order_Date'],dayfirst=True,errors='coerce')
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'],dayfirst=True,errors='coerce') #Nat

In [184]:
cols=['Qty','Unit_Price','Discount']
for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')

In [185]:
df=df[df['Qty']>0]

In [186]:
df['Discount'] = df['Discount'].fillna(0)
df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [187]:
df['Sales']=df['Qty']*df['Unit_Price']

In [188]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Customer_name,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,Neha,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09,Rohit,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08,Amit,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18,Rahul,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,Rahul,39996.0

In [189]:
df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [190]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Customer_name,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,Neha,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09,Rohit,24995.0,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08,Amit,5997.0,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18,Rahul,1497.0,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,Rahul,39996.0,39996.0

In [191]:
#example profit 20%
df['Profit']=df['Net_Amount']*0.20

In [192]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Customer_name,Sales,Net_Amount,Profit
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,Neha,7996.0,7996.0,1599.2
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-02-09,Rohit,24995.0,24995.0,4999.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-05-08,Amit,5997.0,5997.0,1199.4
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-18,Rahul,1497.0,1497.0,299.4
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,Rahul,39996.0,39996.0,7999.2

In [193]:
df['Month']=df['Order_Date'].dt.month_name()

In [194]:
df['Year']=df['Order_Date'].dt.year

In [195]:
df['Weekday']=df['Order_Date'].dt.day_name()

In [196]:
df.info()

<class 'pandas.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       380 non-null    str
 1   Order_Date     333 non-null    datetime64[us]
 2   Customer_Name  380 non-null    str
 3   Email          380 non-null    str
 4   Phone          366 non-null    float64
 5   City           380 non-null    str
 6   State          380 non-null    str
 7   Product        380 non-null    str
 8   Category       380 non-null    str
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    str
 13  Order_Status   380 non-null    str
 14  Delivery_Date  378 non-null    datetime64[us]
 15  Customer_name  380 non-null    str
 16  Sales          343 non-null    float64
 17  Net_Amount     343 non-null    float64
 18  Profit         343 non-null    float64
 19  Month          333 non-null    str
 20  Year           333 non-null    float64
 21  Weekday        333 non-null    str
dtypes: datetime64[us](2), float64(8), str(12)
memory usage: 68.3 KB

In [197]:
df.isnull().sum()

Order_ID          0
Order_Date       47
Customer_Name     0
Email             0
Phone            14
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       37
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Customer_name     0
Sales            37
Net_Amount       37
Profit           37
Month            47
Year             47
Weekday          47
dtype: int64

In [198]:
df.describe()

,Order_Date,Phone,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,333,3.660000e+02,380.000000,343.000000,380.0,378,343.000000,343.000000,343.000000,333.0
mean,2025-04-02 17:35:08.108108,9.545665e+09,3.328947,3252.352770,0.0,2025-04-10 08:41:54.285714,11103.664723,11103.664723,2220.732945,2025.0
min,2025-01-01 00:00:00,9.104441e+09,1.000000,499.000000,0.0,2025-01-05 00:00:00,499.000000,499.000000,99.800000,2025.0
25%,2025-02-14 00:00:00,9.312011e+09,2.000000,999.000000,0.0,2025-02-23 00:00:00,2599.000000,2599.000000,519.800000,2025.0
50%,2025-04-05 00:00:00,9.532803e+09,3.000000,1999.000000,0.0,2025-04-13 00:00:00,5997.000000,5997.000000,1199.400000,2025.0
75%,2025-05-16 00:00:00,9.794651e+09,5.000000,4999.000000,0.0,2025-05-25 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,9.999074e+09,5.000000,9999.000000,0.0,2025-07-08 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,2.673481e+08,1.458196,3026.092014,0.0,NaN,12194.528486,12194.528486,2438.905697,0.0

In [199]:
df.to_csv('Clean_Ecommerce.csv',index=False)

In [200]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Email', 'Phone', 'City',
       'State', 'Product', 'Category', 'Qty', 'Unit_Price', 'Discount',
       'Payment_Mode', 'Order_Status', 'Delivery_Date', 'Customer_name',
       'Sales', 'Net_Amount', 'Profit', 'Month', 'Year', 'Weekday'],
      dtype='str')

In [201]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Payment_Mode,Order_Status,Delivery_Date,Customer_name,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,UPI,Pending,2025-07-03,Neha,7996.0,7996.0,1599.2,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,Card,Pending,2025-02-09,Rohit,24995.0,24995.0,4999.0,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,COD,Returned,2025-05-08,Amit,5997.0,5997.0,1199.4,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,Wallet,Cancelled,2025-02-18,Rahul,1497.0,1497.0,299.4,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,Up,Mouse,Electronics,4.0,...,Card,Returned,2025-02-27,Rahul,39996.0,39996.0,7999.2,February,2025.0,Monday

In [202]:
df.rename(columns={'Customer_name': 'Customer_Name_2'}, inplace=True)

In [203]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Payment_Mode,Order_Status,Delivery_Date,Customer_Name_2,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,UPI,Pending,2025-07-03,Neha,7996.0,7996.0,1599.2,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,Card,Pending,2025-02-09,Rohit,24995.0,24995.0,4999.0,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,COD,Returned,2025-05-08,Amit,5997.0,5997.0,1199.4,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,Wallet,Cancelled,2025-02-18,Rahul,1497.0,1497.0,299.4,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,Up,Mouse,Electronics,4.0,...,Card,Returned,2025-02-27,Rahul,39996.0,39996.0,7999.2,February,2025.0,Monday

In [204]:
df.shape

(380, 22)

In [205]:
from sqlalchemy import create_engine
engine=create_engine('mysql+pymysql://root:root@localhost/ecommerce')

In [206]:
df.to_sql(
    name='orders',
    con=engine,
    if_exists='replace',
    index=False
)

380

In [207]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Payment_Mode,Order_Status,Delivery_Date,Customer_Name_2,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,...,UPI,Pending,2025-07-03,Neha,7996.0,7996.0,1599.2,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,...,Card,Pending,2025-02-09,Rohit,24995.0,24995.0,4999.0,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,COD,Returned,2025-05-08,Amit,5997.0,5997.0,1199.4,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9.517780e+09,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,Wallet,Cancelled,2025-02-18,Rahul,1497.0,1497.0,299.4,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,Up,Mouse,Electronics,4.0,...,Card,Returned,2025-02-27,Rahul,39996.0,39996.0,7999.2,February,2025.0,Monday